"use client";

import { useState, type FormEvent } from "react";
import { ArrowRight, Box, Check, CircleHelp, Clock3, Eye, EyeOff, Gift, Infinity as InfinityIcon, LockKeyhole, LogIn, LogOut, Mail, Package, ShieldCheck, Sparkles, Ticket, UserRound, Wallet, Zap } from "lucide-react";
import { cases } from "@/lib/catalog";
import type { GameState } from "@/lib/types";
import type { GameAction } from "@/components/game-views";
import { Coin, Logo, Modal, Spinner } from "@/components/ui";

export function AuthDialog({ onClose, onSuccess, initialMode = "login" }: { onClose: () => void; onSuccess: (state: GameState) => void; initialMode?: "login" | "register" }) {
  const [mode, setMode] = useState(initialMode);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError(""); setBusy(true);
    try {
      const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: mode, name, email, password }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Не удалось войти. Попробуй ещё раз.");
      onSuccess(data); onClose();
    } catch (error) { setError(error instanceof Error ? error.message : "Ошибка соединения."); }
    finally { setBusy(false); }
  };
  return <Modal title={mode === "login" ? "С возвращением!" : "Твоя история начинается здесь"} onClose={onClose} className="auth-modal"><div className="auth-decoration"><Logo small/></div><p className="modal-subtitle">{mode === "login" ? "Твои скины уже заждались. Продолжим?" : "Сохрани свой дроп. Играй с любого устройства."}</p><div className="auth-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => { setMode("login"); setError(""); }}>Вход</button><button className={mode === "register" ? "active" : ""} onClick={() => { setMode("register"); setError(""); }}>Регистрация</button></div><form onSubmit={submit} className="auth-form">{mode === "register" && <label>Никнейм<div className="input-wrap"><UserRound size={17}/><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Как тебя называть?" minLength={2} maxLength={24} autoComplete="nickname" required/></div></label>}<label>Email<div className="input-wrap"><Mail size={17}/><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" maxLength={254} required/></div></label><label>Пароль<div className="input-wrap"><LockKeyhole size={17}/><input type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Минимум 8 символов" minLength={8} maxLength={128} autoComplete={mode === "register" ? "new-password" : "current-password"} required/><button type="button" className="icon-button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Скрыть пароль" : "Показать пароль"}>{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" type="submit" disabled={busy}>{busy ? <Spinner/> : <>{mode === "login" ? <LogIn size={17}/> : <Sparkles size={17}/>} {mode === "login" ? "Войти в аккаунт" : "Создать аккаунт"}<ArrowRight size={17}/></>}</button></form><div className="auth-note"><ShieldCheck size={17}/><p>{mode === "register" ? "При регистрации гостевой баланс, предметы и история останутся с тобой." : "Вход запоминается на 30 дней. Пароли хранятся только в зашифрованном виде."}</p></div><p className="auth-legal">Бесплатный симулятор. Никаких реальных платежей или вывода предметов.</p></Modal>;
}

export function BonusDialog({ state, act, onClose }: { state: GameState | null; act: GameAction; onClose: () => void }) {
  const [code, setCode] = useState("WVFSTART");
  const [busy, setBusy] = useState("");
  const nextDaily = state?.user.dailyAt ? new Date(new Date(state.user.dailyAt).getTime() + 86400000) : null;
  const ready = !nextDaily || nextDaily.getTime() <= Date.now();
  const claim = async (action: string) => { if (busy) return; setBusy(action); await act({ action, code }); setBusy(""); };
  return <Modal title="Больше монет. Больше эмоций." onClose={onClose} className="bonus-modal"><span className="modal-eyebrow">ТВОЯ ЕЖЕДНЕВНАЯ ПРИВИЛЕГИЯ</span><p className="modal-subtitle">Не нужно платить, чтобы получить хороший дроп.</p><div className="bonus-balance"><span><Wallet size={18}/> Твой баланс</span><Coin value={state?.user.coins || 0}/></div><div className="reward-card daily-card"><div className="reward-icon"><Gift size={29}/></div><div><span className="eyebrow">КАЖДЫЙ ДЕНЬ</span><h3>Ежедневный бонус</h3><strong>+2 500 <span>G</span></strong><p>{ready ? "Твой небольшой ритуал большой удачи." : `Снова доступен ${nextDaily?.toLocaleString("ru-RU", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}`}</p></div><button className="primary-button compact" disabled={!ready || !!busy || !state} onClick={() => claim("daily")}>{busy === "daily" ? <Spinner/> : ready ? <>Забрать <ArrowRight size={15}/></> : <><Check size={15}/> Получен</>}</button></div><div className="reward-card refill-card"><div className="reward-icon"><InfinityIcon size={28}/></div><div><h3>Игра без ограничений</h3><p>Ещё 5 000 G. Бесплатно. Сколько захочешь.</p></div><button className="secondary-button compact" disabled={!!busy || !state} onClick={() => claim("refill")}>{busy === "refill" ? <Spinner/> : <>+5 000 <span className="coin-symbol">G</span></>}</button></div><form className="promo-form" onSubmit={(e) => { e.preventDefault(); void claim("promo"); }}><label htmlFor="promo-code"><Ticket size={16}/> Есть промокод?</label><div><input id="promo-code" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Введи промокод" maxLength={40} disabled={state?.user.promoClaimed} required/><button className="secondary-button" disabled={!!busy || !state || state.user.promoClaimed} type="submit">{busy === "promo" ? <Spinner/> : state?.user.promoClaimed ? <><Check size={15}/> Активирован</> : "Активировать"}</button></div><small>WVFSTART — 1 500 G для яркого старта. Один раз на аккаунт.</small></form><div className="saved-label"><ShieldCheck size={14}/> Все монеты виртуальные. Платёжные данные не нужны.</div></Modal>;
}

export function ProfileDialog({ state, onClose, onLogout, onInventory }: { state: GameState; onClose: () => void; onLogout: () => Promise<void>; onInventory: () => void }) {
  const [busy, setBusy] = useState(false);
  return <Modal title="Твой аккаунт" onClose={onClose} className="profile-modal"><div className="profile-modal-avatar">{state.user.name[0]}</div><h3>{state.user.name}</h3><p className="modal-subtitle">{state.user.email}</p><div className="profile-details"><div><span>Виртуальный баланс</span><Coin value={state.user.coins}/></div><div><span>Предметов в коллекции</span><strong>{state.inventory.length}</strong></div><div><span>Открыто кейсов</span><strong>{state.user.opened}</strong></div><div><span>С нами с</span><strong>{new Date(state.user.createdAt).toLocaleDateString("ru-RU")}</strong></div></div><button className="primary-button auth-submit" onClick={() => { onClose(); onInventory(); }}><Package size={17}/> Мой инвентарь <ArrowRight size={17}/></button><button className="text-button logout-button" disabled={busy} onClick={async () => { setBusy(true); await onLogout(); setBusy(false); }}>{busy ? <Spinner/> : <><LogOut size={15}/> Выйти из аккаунта</>}</button><p className="auth-legal">Прогресс сохранён. Войди снова, чтобы продолжить.</p></Modal>;
}

export function InfoDialog({ kind, onClose, onStart }: { kind: "how" | "fair" | "rules"; onClose: () => void; onStart: () => void }) {
  const [expanded, setExpanded] = useState<number | null>(0);
  const faqs = [
    ["Это действительно бесплатно?", "Да. На старте ты получаешь 5 000 виртуальных монет G. Бесплатный кейс можно открывать без ограничений, а баланс — пополнять в разделе «Бонусы» без банковской карты и платежей."],
    ["Можно ли вывести предметы в Steam?", "Нет. WVFCASE — самостоятельный визуальный симулятор. Предметы существуют только внутри сайта, не имеют денежной стоимости и не могут быть обменены или выведены."],
    ["Как сохранить свой прогресс?", "Гостевой прогресс привязан к защищённой сессии браузера на 30 дней. Создай аккаунт, чтобы сохранить доступ на будущее и входить с других устройств. При регистрации все гостевые предметы и баланс остаются с тобой."],
    ["Как работает апгрейд?", "Выбери свой предмет и более дорогую цель. Шанс равен отношению их виртуальных цен, умноженному на 85%, но не больше 75%. При успехе ты получишь цель, при неудаче исходный предмет будет использован."],
    ["Какие кейсы есть на сайте?", `В каталоге ${cases.length} кейса: 12 авторских коллекций WVFCASE и 42 стандартных кейса из открытого каталога CS2. На странице каждого кейса можно посмотреть все предметы и вероятность выпадения каждого.`],
  ];
  return <Modal title={kind === "how" ? "Большой дроп. Ноль сложностей." : kind === "fair" ? "Честная игра — открытые шансы" : "Здесь играют ради эмоций"} onClose={onClose} className="info-modal">{kind === "how" ? <><p className="modal-subtitle">Всё, что нужно знать перед первым открытием.</p><div className="how-steps">{[{ icon: Gift, title: "Забери монеты", text: "5 000 G уже на старте. Бонусы — каждый день." }, { icon: Box, title: "Выбери свой кейс", text: `${cases.length} коллекции и сотни крутых скинов.` }, { icon: Package, title: "Собери коллекцию", text: "Сохраняй, улучшай и создавай контракты." }].map((step, i) => <div key={step.title}><span className="how-number">0{i + 1}</span><step.icon size={24}/><h3>{step.title}</h3><p>{step.text}</p></div>)}</div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${expanded === i ? "expanded" : ""}`} key={question}><button onClick={() => setExpanded(expanded === i ? null : i)} aria-expanded={expanded === i}>{question}<span>{expanded === i ? "−" : "+"}</span></button>{expanded === i && <p>{answer}</p>}</div>)}</div><button className="primary-button auth-submit" onClick={onStart}>Открыть первый кейс <ArrowRight size={16}/></button></> : kind === "fair" ? <div className="prose-content"><ShieldCheck size={42}/><p>Результат выбирается на сервере криптографическим генератором случайных чисел. Анимация только показывает уже сохранённый результат и не влияет на него.</p><h3>Вероятности доступны каждому</h3><p>Точный шанс указан на карточке каждого предмета в содержимом кейса. Сумма вероятностей всех предметов — 100% с учётом округления. У разных кейсов разный набор предметов и распределение шансов.</p><h3>Никаких реальных ставок</h3><p>Все цены условные и выражены в виртуальных G. Они не отражают цены Steam. Наши вероятности не повторяют и не представляют официальные вероятности Valve.</p><h3>Всё сохраняется</h3><p>Монеты списываются, а предмет добавляется в одной транзакции базы данных. Даже если закрыть страницу во время анимации, выигранный предмет останется в инвентаре.</p></div> : <div className="prose-content"><Sparkles size={42}/><p>WVFCASE — бесплатный развлекательный симулятор открытия кейсов, а не казино, торговая площадка или сервис реальных ставок.</p><h3>Виртуальная коллекция</h3><p>Предметы и монеты не имеют денежной ценности. Здесь нет депозитов, платежей, обменов между пользователями и вывода в Steam.</p><h3>Аккаунт и данные</h3><p>Мы сохраняем никнейм, email, хеш пароля, инвентарь и игровую историю в базе данных. Сессия хранится в защищённом HttpOnly cookie. Не используй пароль от Steam или другого важного аккаунта.</p><h3>Независимый проект</h3><p>WVFCASE не связан с Valve, Steam, Upgrade или Bulldrop. Названия и изображения игровых предметов принадлежат соответствующим правообладателям. Иллюстрации авторских кейсов созданы для этого проекта.</p></div>}</Modal>;
}
